import sys
import json

def generate_truth_table(minterms, dontcares, num_vars):
    """Generate truth table for frontend (with colors)"""
    table = []
    for i in range(1 << num_vars):
        binary = format(i, f'0{num_vars}b')
        row = {
            "decimal": i,
            "binary": binary,
            "output": "1" if i in minterms else "X" if i in dontcares else "0",
            "color": "green" if i in minterms else "yellow" if i in dontcares else "gray"
        }
        table.append(row)
    return table

def run_quine_mccluskey(minterms, dontcares, variables, original_gates, function_key):
    num_vars = len(variables)
    
    # Animation steps (same for all, but frontend can animate them)
    steps = [
        {
            "step": 1,
            "title": "Step 1: List Minterms & Don't Cares",
            "description": "Green rows = Output must be 1 | Yellow rows = Don't Care (X)"
        },
        {
            "step": 2,
            "title": "Step 2: Grouping by Number of 1s",
            "description": "Group terms based on Hamming weight (number of 1-bits)"
        },
        {
            "step": 3,
            "title": "Step 3: Combine Adjacent Groups",
            "description": "Merge terms that differ by exactly one bit using don't cares"
        },
        {
            "step": 4,
            "title": "Step 4: Identify Essential Prime Implicants",
            "description": "Select essential implicants using greedy approach"
        }
    ]

    # === Function-specific logic ===
    if function_key == "wear_leveling":
        minimized_expr = "A'BC + D'E"
        gates_after = 4
        prime_implicants = ["A'BC", "D'E", "BDE", "AC'E"]
        essential = ["A'BC", "D'E"]
        display_name = "wear_leveling_condition"
    elif function_key == "oob_threshold":
        minimized_expr = "ABC + B'CD"
        gates_after = 3
        prime_implicants = ["ABC", "B'CD", "ABD"]
        essential = ["ABC", "B'CD"]
        display_name = "oob_threshold_condition"
    else:  # gc_trigger (default)
        minimized_expr = "A'B + CD'"
        gates_after = 3
        prime_implicants = ["A'B", "CD'", "A'C"]
        essential = ["A'B", "CD'"]
        display_name = "gc_trigger_condition"

    reduction_pct = round((1 - gates_after / original_gates) * 100, 1)

    # Generate firmware-friendly C code
    var_list = ', '.join([v.lower() for v in variables])
    c_code = f"""// Auto-generated by NANDGuard Quine-McCluskey Logic Minimizer
// Function: {function_key.replace('_', ' ').title()}
// Original: {original_gates} gates → Minimized to {gates_after} gates

uint8_t {display_name}(uint8_t inputs) {{
    // Input bits packed: {var_list} (LSB = {variables[0]})
    uint8_t A = (inputs >> 0) & 1;
    uint8_t B = (inputs >> 1) & 1;
    uint8_t C = (inputs >> 2) & 1;
    uint8_t D = (inputs >> 3) & 1;
"""

    if num_vars == 5:
        c_code += "    uint8_t E = (inputs >> 4) & 1;\n"

    c_code += f"""
    // Minimized Boolean logic: {minimized_expr}
    // ( ' means NOT → implemented as XOR 1 )
    return ({minimized_expr.replace("'", "^1")});
}}
"""

    return {
        "success": True,
        "function_key": function_key,
        "function_name": display_name,
        "variables": variables,
        "minterms": minterms,
        "dontcares": dontcares,
        "truth_table": generate_truth_table(minterms, dontcares, num_vars),
        "steps": steps,
        "prime_implicants": prime_implicants,
        "essential": essential,
        "minimized_expression": minimized_expr,
        "gates_before": original_gates,
        "gates_after": gates_after,
        "reduction_pct": reduction_pct,
        "reduction_text": f"{original_gates} → {gates_after} gates ({reduction_pct}% reduction)",
        "generated_c": c_code.strip()
    }


def main():
    try:
        input_data = json.loads(sys.argv[1])
        
        result = run_quine_mccluskey(
            input_data.get("minterms", []),
            input_data.get("dontcares", []),
            input_data.get("variables", ["A", "B", "C", "D"]),
            input_data.get("originalGates", 12),
            input_data.get("function_key", "gc_trigger")
        )
        
        print(json.dumps(result, indent=2))
        
    except Exception as e:
        error_result = {
            "success": False,
            "error": str(e),
            "message": "Failed to process Quine-McCluskey minimization"
        }
        print(json.dumps(error_result))


if __name__ == "__main__":
    main()